name: car_rental
dependencies:
- python=3.5
- pip
- pip:
  - toolz==0.9.0
  - scikit-learn==0.21.2
  - pillow==4.0
  - h5py==2.9.0
  - jupyter
  - matplotlib==3.0.3
  - pandas==0.20.3
  - seaborn==0.9.0
  - plotly==3.0
  - imbalanced-learn==0.5.0
  - seaborn==0.9.0
  - xgboost==0.90
  - xlrd==1.2.0
  - nltk==3.4.5
  - openpyxl==2.6.3
  - statsmodels
